version: '3.5'

services:

  service-zon-coffee:
    image: kunthysen/zon-coffee:2.0.0
    ports:
      - 8082:80
    deploy:
      mode: global
      #replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure


  service-eflyer:
    image: kunthysen/eflyer:2.0.0
    ports:
      - 8081:80
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure


  service-beautiflie:
    image: kunthysen/beatutiflie:2.0.0
    ports:
      - 80:80
    deploy:
      mode: global
      #replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
